In [55]:
import numpy as np
from PIL import Image
import ctypes
import matplotlib.pyplot as plt
import random

In [56]:
asia = Image.open('test_images/asia.jpg')
greek = Image.open('test_images/greek.jpg')
south_america = Image.open('test_images/south_america.jpg')
image_a_predire = Image.open('test_images/to_predict.jpg')

In [57]:
newsize = (27,27)

In [58]:
asia_new_size = asia.resize(newsize)
greek_new_size = greek.resize(newsize)
south_america_new_size = south_america.resize(newsize)
image_a_predire_new_size = image_a_predire.resize(newsize)

In [59]:
# asia_new_size.show()
# greek_new_size.show()
# south_america_new_size.show()

In [60]:
asia_data = np.asarray(asia_new_size)
greek_data = np.asarray(greek_new_size)
south_america_data = np.asarray(south_america_new_size)
image_a_predire_data = np.asarray(image_a_predire_new_size)

X = np.array([asia_data, greek_data, south_america_data], dtype=ctypes.c_float)
X_flat = X.flatten()

In [61]:
print(len(X_flat))

6561


In [62]:
print(len(X))

3


In [63]:
Y = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]], dtype=ctypes.c_float)
Y_flat = Y.flatten()
print(Y_flat)

[ 1. -1. -1. -1.  1. -1. -1. -1.  1.]


In [64]:
my_lib = ctypes.CDLL(r"..\rust_lib\target\debug\rust_lib.dll")

my_lib.delete_float_array.argtypes = [
    ctypes.POINTER(ctypes.c_float),
    ctypes.c_int32,
]

my_lib.generate_random_mpl_w.argtypes = [ctypes.POINTER(ctypes.c_float), ctypes.c_int32]
my_lib.generate_random_mpl_w.restype = ctypes.POINTER(ctypes.c_float)

my_lib.delete_float_array.restype = None

layers = np.array([len(X_flat)/len(X), 16, 16, 16, 16, 3], dtype=ctypes.c_float)
LP_c_float = ctypes.POINTER(ctypes.c_float)
layers_pmc = (ctypes.c_float * len(layers))(*layers)
layers_ptr_pmc = ctypes.cast(layers_pmc, LP_c_float)

print(len(layers_pmc))
number_of_layers = len(layers_pmc)
print(layers)

6
[2187.   16.   16.   16.   16.    3.]


In [65]:
w_array_ptr = my_lib.generate_random_mpl_w(layers_ptr_pmc, number_of_layers)
w_array = np.ctypeslib.as_array(w_array_ptr, ((2188*16 + 17*16 + 17*16 +17*16+ 17*3,))) #3*16 + 17*16 + 17*3

LP_c_float = ctypes.POINTER(ctypes.c_float)
x_to_predict = (ctypes.c_float * len(X_flat))(*X_flat)
x_to_predict_ptr = ctypes.cast(x_to_predict, LP_c_float)
LP_c_float = ctypes.POINTER(ctypes.c_float)
y_to_predict = (ctypes.c_float * len(Y_flat))(*Y_flat)
y_to_predict_ptr = ctypes.cast(y_to_predict, LP_c_float)
my_lib.multi_layer_perceptron_training.argtypes = [
    ctypes.POINTER(ctypes.c_float),
    ctypes.POINTER(ctypes.c_float),
    ctypes.POINTER(ctypes.c_float),
    ctypes.c_int32,
    ctypes.c_int32,
    ctypes.c_int32,
    ctypes.c_float,
    ctypes.c_int32,
    ctypes.POINTER(ctypes.c_float),
    ctypes.c_int32,
    ctypes.c_bool,
]
my_lib.multi_layer_perceptron_training.restype = ctypes.POINTER(ctypes.c_float)

In [66]:
print(len(X))

3


In [67]:
pmc_trained_model_ptr = my_lib.multi_layer_perceptron_training(
    w_array_ptr,
    y_to_predict_ptr,
    x_to_predict_ptr,
    len(X),  # number of inputs
    int(len(X_flat)/len(X)),  # dimension of inputs
    3,  # number of classes to predict
    0.5,  # learning rate
    10,  # epochs
    layers_ptr_pmc,  # pointeur vers la forme de pmc
    number_of_layers,  # number of layers
    True,
)

pmc_trained_model = np.ctypeslib.as_array(pmc_trained_model_ptr, (2188*16 + 17*16 + 17*16 +17*16+ 17*3,))
#print(pmc_trained_model)


In [68]:
# asia_data = np.asarray(asia_new_size)
# greek_data = np.asarray(greek_new_size)
# south_america_data = np.asarray(south_america_new_size)
image_a_predire_data = np.array([image_a_predire_data],dtype=ctypes.c_float)
image_a_predire_data_flat=image_a_predire_data.flatten()
# new_X = np.array([south_america_data, asia_data, greek_data], dtype=ctypes.c_float)
# new_flat_X = X.flatten()

In [69]:
print(len(image_a_predire_data))
print(len(image_a_predire_data_flat))

1
2187


In [70]:
my_lib.multi_layer_perceptron_predict.argtypes = [
    ctypes.POINTER(ctypes.c_float),
    ctypes.POINTER(ctypes.c_float),
    ctypes.c_int32,
    ctypes.c_int32,
    ctypes.c_int32,
    ctypes.POINTER(ctypes.c_float),
    ctypes.c_int32,
    ctypes.c_bool,
]

my_lib.multi_layer_perceptron_predict.restype = ctypes.POINTER(ctypes.c_float)

LP_c_float = ctypes.POINTER(ctypes.c_float)
x_to_predict_mlp = (ctypes.c_float * len(image_a_predire_data_flat))(*image_a_predire_data_flat)
x_to_predict_ptr_mlp = ctypes.cast(x_to_predict_mlp, LP_c_float)

pmc_predict_ptr = my_lib.multi_layer_perceptron_predict(
    pmc_trained_model_ptr,  # pointeur vers le modele entrainé
    x_to_predict_ptr_mlp,  # pointeur vers le dataset à prédire
    len(image_a_predire_data),  # nombre d'éléments du dataset
    int(len(image_a_predire_data_flat)/len(image_a_predire_data)),  # dimension des éléments du dataset
    3,  # number of classes to predict
    layers_ptr_pmc,  # pointeur vers la forme de pmc
    number_of_layers,  # number of layers
    True,  # is classification
)

pmc_predict_model = np.ctypeslib.as_array(pmc_predict_ptr, (3 * len(image_a_predire_data),))
# print(pmc_predict_model)
# print(len(X_to_predict))
# print(len(X_to_predict_flat))


In [71]:
for j in range(0,len(pmc_predict_model)-2,3) :
    if pmc_predict_model[j] > pmc_predict_model[j+1] and pmc_predict_model[j] > pmc_predict_model[j+2] :
        print("L'image a deviner vient d'asie")
    elif pmc_predict_model[j+1] > pmc_predict_model[j] and pmc_predict_model[j+1] > pmc_predict_model[j+2] :
        print("L'image a deviner vient de grece")
    elif pmc_predict_model[j+2] > pmc_predict_model[j] and pmc_predict_model[j+2] > pmc_predict_model[j+1]:
        print("L'image a deviner vient d'amerique du sud")
    else :
        print('résultats non concluants')

L'image a deviner vient de grece


In [72]:
print(pmc_predict_model)

[-0.9999999   0.99892205 -0.99490523]


In [70]:
print(pmc_predict_model)

[ 0.95705676 -0.9888257  -0.98240566 -0.96874535  0.9717122  -0.9874089
 -0.99191004 -0.95757884  0.9669857 ]
